import { library } from '@fortawesome/fontawesome-svg-core';
import { config } from '@fortawesome/fontawesome-svg-core';
import {
  faMoneyBillWave,
  faHourglassHalf,
  faCheckCircle,
  faTimesCircle,
  faHistory,
  faDownload,
  faEye,
  faHeadset,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faPaperPlane,
  faTicketAlt,
  faChevronDown,
  faCog,
  faBell,
  faUser,
  faLock,
  faSignOutAlt,
  faArrowRight,
  faGraduationCap,
  faCalendarAlt,
  faFileAlt,
  faSearch,
  faFilter,
  faSort,
  faPlus,
  faEdit,
  faTrash,
  faSave,
  faCancel,
  faUpload,
  faChartBar,
  faUsers,
  faCreditCard,
  faReceipt,
  faExclamationTriangle,
  faInfoCircle,
  faTimes,
  faCheck,
  faBars,
  faHome,
  faDashboard,
  faWallet,
  faFileInvoice,
  faUserGraduate,
  faBullhorn,
  faSchool,
  faQuestionCircle,
  faLifeRing
} from '@fortawesome/free-solid-svg-icons';

// Configure FontAwesome to prevent auto-adding CSS
config.autoAddCss = false;

// Add icons to the library
library.add(
  faMoneyBillWave,
  faHourglassHalf,
  faCheckCircle,
  faTimesCircle,
  faHistory,
  faDownload,
  faEye,
  faHeadset,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faPaperPlane,
  faTicketAlt,
  faChevronDown,
  faCog,
  faBell,
  faUser,
  faLock,
  faSignOutAlt,
  faArrowRight,
  faGraduationCap,
  faCalendarAlt,
  faFileAlt,
  faSearch,
  faFilter,
  faSort,
  faPlus,
  faEdit,
  faTrash,
  faSave,
  faCancel,
  faUpload,
  faChartBar,
  faUsers,
  faCreditCard,
  faReceipt,
  faExclamationTriangle,
  faInfoCircle,
  faTimes,
  faCheck,
  faBars,
  faHome,
  faDashboard,
  faWallet,
  faFileInvoice,
  faUserGraduate,
  faBullhorn,
  faSchool,
  faQuestionCircle,
  faLifeRing
);

export default library;
